grails-app/controllers/grailsmailexample/EmailSenderController.groovy
package grailsmailexample

class EmailSenderController {

    def index() {}

    def send() {
        def multipartFile = request.getFile('attachment')

        sendMail {
            multipart true
            to params.address
            subject params.subject
            html params.body
            if (multipartFile && !multipartFile.empty) {
                File tmpFile = new File(System.getProperty("java.io.tmpdir") + System.getProperty("file.separator") + multipartFile.getOriginalFilename())
                multipartFile.transferTo(tmpFile)
                attach tmpFile
            }
        }

        flash.message = "Message sent at " + new Date()
        redirect action: "index"
    }


}

grails-app/controllers/grailsmailexample/UrlMappings.groovy
package grailsmailexample

class UrlMappings {

    static mappings = {
        "/$controller/$action?/$id?(.$format)?"{
            constraints {
                // apply constraints here
            }
        }

        "/"(view:"/index")
        "500"(view:'/error')
        "404"(view:'/notFound')
    }
}

grails-app/views/emailSender/index.gsp
<!doctype html>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Email Sender</title>

    <asset:link rel="icon" href="favicon.ico" type="image/x-ico"/>

    <script src="//cdn.ckeditor.com/4.6.0/full-all/ckeditor.js"></script>
</head>

<body>
<div id="content" role="main">
    <section class="row colset-2-its">
        <g:if test="${flash.message}">
            <div class="message" role="alert">
                ${flash.message}
            </div>
        </g:if>
        <h2>Email Sender Form</h2>
        <g:form controller="emailSender" action="send" enctype="multipart/form-data">
            <div class="fieldcontain">
                <g:textField name="address" placeholder="youremail@gmail.com" required=""/>
            </div>

            <div class="fieldcontain">
                <g:textField name="subject" placeholder="Your Subject" required=""/>
            </div>

            <div class="fieldcontain">
                <g:textArea name="body" rows="5" cols="80" placeholder="Your message" required=""/>
            </div>

            <div class="fieldcontain">
                <input type="file" name="attachment"/>
            </div>

            <fieldset>
                <g:submitButton name="send" value="Send"/>
            </fieldset>
        </g:form>
    </section>
</div>

<script>
    CKEDITOR.replace('body', {
        extraPlugins: 'codesnippet'
    });
</script>

</body>
</html>

grails-app/views/layouts/main.gsp
<!doctype html>
<html lang="en" class="no-js">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <title>
        <g:layoutTitle default="Grails"/>
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <asset:link rel="icon" href="favicon.ico" type="image/x-ico"/>

    <asset:stylesheet src="application.css"/>

    <g:layoutHead/>
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-dark navbar-static-top" role="navigation">
    <a class="navbar-brand" href="/#"><asset:image src="grails.svg" alt="Grails Logo"/></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent"
            aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" aria-expanded="false" style="height: 0.8px;" id="navbarContent">
        <ul class="nav navbar-nav ml-auto">
            <g:pageProperty name="page.nav"/>
        </ul>
    </div>

</nav>

<g:layoutBody/>

<div class="footer row" role="contentinfo">
    <div class="col">
        <a href="http://guides.grails.org" target="_blank">
            <asset:image src="advancedgrails.svg" alt="Grails Guides" class="float-left"/>
        </a>
        <strong class="centered"><a href="http://guides.grails.org" target="_blank">Grails Guides</a></strong>

        <p>Building your first Grails app? Looking to add security, or create a Single-Page-App? Check out the <a
                href="http://guides.grails.org" target="_blank">Grails Guides</a> for step-by-step tutorials.</p>

    </div>

    <div class="col">
        <a href="http://docs.grails.org" target="_blank">
            <asset:image src="documentation.svg" alt="Grails Documentation" class="float-left"/>
        </a>
        <strong class="centered"><a href="http://docs.grails.org" target="_blank">Documentation</a></strong>

        <p>Ready to dig in? You can find in-depth documentation for all the features of Grails in the <a
                href="http://docs.grails.org" target="_blank">User Guide</a>.</p>

    </div>

    <div class="col">
        <a href="https://grails-slack.cfapps.io" target="_blank">
            <asset:image src="slack.svg" alt="Grails Slack" class="float-left"/>
        </a>
        <strong class="centered"><a href="https://grails-slack.cfapps.io" target="_blank">Join the Community</a>
        </strong>

        <p>Get feedback and share your experience with other Grails developers in the community <a
                href="https://grails-slack.cfapps.io" target="_blank">Slack channel</a>.</p>
    </div>
</div>


<div id="spinner" class="spinner" style="display:none;">
    <g:message code="spinner.alt" default="Loading&hellip;"/>
</div>

<asset:javascript src="application.js"/>

</body>
</html>